server:
  port: 8090
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gym_system?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2b8
    username: root
    password: Ylc0612.
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        max-active: 50
        max-idle: 50
        min-idle: 0
        max-wait: -1ms
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
aliyun:
  oos:
    file:
      Endpoint: https://oss-cn-hangzhou.aliyuncs.com
      AccessKeyId: LTAI5t7tMdo9dob2UYC7suSV
      AccessKeySecret: DQFUCisk9rlewDBvIqCXZKf6kRHfkS
      BucketName: yangliccc-gym